/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// Provides detailed information about a submitted command.  <p>There are two types of commands: synchronous and asynchronous. Synchronous commands complete immediately, and their results are passed back in the returned command object after the execution of an API call. Outside of that returned object, there is no way to check the result of a synchronous command.</p>  <p>Asynchronous commands have unique non-negative IDs. They may still be running when the API call returns. Clients can check the status of such commands using the API.</p>
type ApiCommand struct {
	// The command ID.
	Id float64 `json:"id,omitempty"`
	// The command name.
	Name string `json:"name,omitempty"`
	// The start time.
	StartTime string `json:"startTime,omitempty"`
	// The end time, if the command is finished.
	EndTime string `json:"endTime,omitempty"`
	// Whether the command is currently active.
	Active bool `json:"active,omitempty"`
	// If the command is finished, whether it was successful.
	Success bool `json:"success,omitempty"`
	// If the command is finished, the result message.
	ResultMessage string `json:"resultMessage,omitempty"`
	// URL to the command's downloadable result data, if any exists.
	ResultDataUrl string          `json:"resultDataUrl,omitempty"`
	ClusterRef    *ApiClusterRef  `json:"clusterRef,omitempty"`
	ServiceRef    *ApiServiceRef  `json:"serviceRef,omitempty"`
	RoleRef       *ApiRoleRef     `json:"roleRef,omitempty"`
	HostRef       *ApiHostRef     `json:"hostRef,omitempty"`
	Parent        *ApiCommand     `json:"parent,omitempty"`
	Children      *ApiCommandList `json:"children,omitempty"`
	// If the command can be retried. Available since V11
	CanRetry bool `json:"canRetry,omitempty"`
}
