/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ApiEntityStatus : The single value used by the Cloudera Manager UI to represent the status of the entity. It is computed from a variety of other entity-specific states, not all values apply to all entities. For example, STARTING/STOPPING do not apply to a host.
type ApiEntityStatus string

// List of ApiEntityStatus
const (
	UNKNOWN_ApiEntityStatus               ApiEntityStatus = "UNKNOWN"
	NONE_ApiEntityStatus                  ApiEntityStatus = "NONE"
	STOPPED_ApiEntityStatus               ApiEntityStatus = "STOPPED"
	DOWN_ApiEntityStatus                  ApiEntityStatus = "DOWN"
	UNKNOWN_HEALTH_ApiEntityStatus        ApiEntityStatus = "UNKNOWN_HEALTH"
	DISABLED_HEALTH_ApiEntityStatus       ApiEntityStatus = "DISABLED_HEALTH"
	CONCERNING_HEALTH_ApiEntityStatus     ApiEntityStatus = "CONCERNING_HEALTH"
	BAD_HEALTH_ApiEntityStatus            ApiEntityStatus = "BAD_HEALTH"
	GOOD_HEALTH_ApiEntityStatus           ApiEntityStatus = "GOOD_HEALTH"
	STARTING_ApiEntityStatus              ApiEntityStatus = "STARTING"
	STOPPING_ApiEntityStatus              ApiEntityStatus = "STOPPING"
	HISTORY_NOT_AVAILABLE_ApiEntityStatus ApiEntityStatus = "HISTORY_NOT_AVAILABLE"
)
