/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

type ApiHdfsUsageReportRow struct {
	// The date of the report row data.
	Date string `json:"date,omitempty"`
	// The user being reported.
	User string `json:"user,omitempty"`
	// Total size (in bytes) of the files owned by this user. This does not include replication in HDFS.
	Size float64 `json:"size,omitempty"`
	// Total size (in bytes) of all the replicas of all the files owned by this user.
	RawSize float64 `json:"rawSize,omitempty"`
	// Number of files owned by this user.
	NumFiles float64 `json:"numFiles,omitempty"`
}
