/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ScmDbType : Enum for Cloudera Manager DB type. Note that DERBY and SQLITE3 are not supported DBs
type ScmDbType string

// List of ScmDbType
const (
	MYSQL_ScmDbType      ScmDbType = "MYSQL"
	POSTGRESQL_ScmDbType ScmDbType = "POSTGRESQL"
	HSQL_ScmDbType       ScmDbType = "HSQL"
	ORACLE_ScmDbType     ScmDbType = "ORACLE"
	DERBY_ScmDbType      ScmDbType = "DERBY"
	SQLITE3_ScmDbType    ScmDbType = "SQLITE3"
)
