/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ZooKeeperServerMode : The state of the Zookeeper server.
type ZooKeeperServerMode string

// List of ZooKeeperServerMode
const (
	STANDALONE_ZooKeeperServerMode                 ZooKeeperServerMode = "STANDALONE"
	REPLICATED_FOLLOWER_ZooKeeperServerMode        ZooKeeperServerMode = "REPLICATED_FOLLOWER"
	REPLICATED_LEADER_ZooKeeperServerMode          ZooKeeperServerMode = "REPLICATED_LEADER"
	REPLICATED_LEADER_ELECTION_ZooKeeperServerMode ZooKeeperServerMode = "REPLICATED_LEADER_ELECTION"
	REPLICATED_OBSERVER_ZooKeeperServerMode        ZooKeeperServerMode = "REPLICATED_OBSERVER"
	UNKNOWN_ZooKeeperServerMode                    ZooKeeperServerMode = "UNKNOWN"
)
