/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// Arguments used for the Cloudera Manager level performance inspector. Network diagnostics will be run from every host in sourceCluster to every host in targetCluster.
type ApiClustersPerfInspectorArgs struct {
	// Required name of the source cluster to run network diagnostics test.
	SourceCluster string `json:"sourceCluster,omitempty"`
	// Required name of the target cluster to run network diagnostics test.
	TargetCluster string                         `json:"targetCluster,omitempty"`
	PingArgs      *ApiPerfInspectorPingArgs      `json:"pingArgs,omitempty"`
	BandwidthArgs *ApiPerfInspectorBandwidthArgs `json:"bandwidthArgs,omitempty"`
	PolicyType    *PerfInspectorPolicyType       `json:"policyType,omitempty"`
}
