/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// This is the model for user role scope in the API since v18. This is used to support granular permissions.
type ApiAuthRole struct {
	DisplayName          string                      `json:"displayName,omitempty"`
	Name                 string                      `json:"name,omitempty"`
	Clusters             []ApiClusterRef             `json:"clusters,omitempty"`
	Users                []ApiUser2Ref               `json:"users,omitempty"`
	ExternalUserMappings []ApiExternalUserMappingRef `json:"externalUserMappings,omitempty"`
	BaseRole             *ApiAuthRoleRef             `json:"baseRole,omitempty"`
	// Readonly. The UUID of the authRole. <p>
	Uuid     string `json:"uuid,omitempty"`
	IsCustom bool   `json:"isCustom,omitempty"`
}
