/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// This object is used to represent a host within an ApiParcelUsage.
type ApiParcelUsageHost struct {
	HostRef *ApiHostRef `json:"hostRef,omitempty"`
	// A collection of the roles present on the host.
	Roles []ApiParcelUsageRole `json:"roles,omitempty"`
}
