/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

type ApiActivityType string

// List of ApiActivityType
const (
	UNKNOWN_ApiActivityType   ApiActivityType = "UNKNOWN"
	OOZIE_ApiActivityType     ApiActivityType = "OOZIE"
	PIG_ApiActivityType       ApiActivityType = "PIG"
	HIVE_ApiActivityType      ApiActivityType = "HIVE"
	MR_ApiActivityType        ApiActivityType = "MR"
	STREAMING_ApiActivityType ApiActivityType = "STREAMING"
)
