/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// Utilization report information of a tenant of Impala application.
type ApiImpalaTenantUtilization struct {
	// Name of the tenant.
	TenantName string `json:"tenantName,omitempty"`
	// Total number of queries submitted to Impala.
	TotalQueries float64 `json:"totalQueries,omitempty"`
	// Number of queries that finished successfully.
	SuccessfulQueries float64 `json:"successfulQueries,omitempty"`
	// Number of queries that failed due to insufficient memory.
	OomQueries float64 `json:"oomQueries,omitempty"`
	// Number of queries that timed out while waiting for resources in a pool.
	TimeOutQueries float64 `json:"timeOutQueries,omitempty"`
	// Number of queries that were rejected by Impala because the pool was full.
	RejectedQueries float64 `json:"rejectedQueries,omitempty"`
	// Average time, in milliseconds, spent by a query in an Impala pool while waiting for resources.
	AvgWaitTimeInQueue float64 `json:"avgWaitTimeInQueue,omitempty"`
	// The time when Impala reserved the maximum amount of memory for queries.
	PeakAllocationTimestampMS float64 `json:"peakAllocationTimestampMS,omitempty"`
	// The maximum memory (in bytes) that was reserved by Impala for executing queries.
	MaxAllocatedMemory float64 `json:"maxAllocatedMemory,omitempty"`
	// The maximum percentage of memory that was reserved by Impala for executing queries.
	MaxAllocatedMemoryPercentage float64 `json:"maxAllocatedMemoryPercentage,omitempty"`
	// The amount of memory (in bytes) used by Impala for running queries at the time when maximum memory was reserved.
	UtilizedAtMaxAllocated float64 `json:"utilizedAtMaxAllocated,omitempty"`
	// The percentage of memory used by Impala for running queries at the time when maximum memory was reserved.
	UtilizedAtMaxAllocatedPercentage float64 `json:"utilizedAtMaxAllocatedPercentage,omitempty"`
	// The time when Impala used the maximum amount of memory for queries.
	PeakUsageTimestampMS float64 `json:"peakUsageTimestampMS,omitempty"`
	// The maximum memory (in bytes) that was used by Impala for executing queries.
	MaxUtilizedMemory float64 `json:"maxUtilizedMemory,omitempty"`
	// The maximum percentage of memory that was used by Impala for executing queries.
	MaxUtilizedMemoryPercentage float64 `json:"maxUtilizedMemoryPercentage,omitempty"`
	// The amount of memory (in bytes) reserved by Impala at the time when it was using the maximum memory for executing queries.
	AllocatedAtMaxUtilized float64 `json:"allocatedAtMaxUtilized,omitempty"`
	// The percentage of memory reserved by Impala at the time when it was using the maximum memory for executing queries.
	AllocatedAtMaxUtilizedPercentage    float64                        `json:"allocatedAtMaxUtilizedPercentage,omitempty"`
	DistributionUtilizedByImpalaDaemon  *ApiImpalaUtilizationHistogram `json:"distributionUtilizedByImpalaDaemon,omitempty"`
	DistributionAllocatedByImpalaDaemon *ApiImpalaUtilizationHistogram `json:"distributionAllocatedByImpalaDaemon,omitempty"`
	// Average spill per query.
	AvgSpilledMemory float64 `json:"avgSpilledMemory,omitempty"`
	// Maximum spill per query.
	MaxSpilledMemory float64 `json:"maxSpilledMemory,omitempty"`
}
