/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ApiScheduleInterval : Represents the unit for the repeat interval for schedules.
type ApiScheduleInterval string

// List of ApiScheduleInterval
const (
	MINUTE_ApiScheduleInterval ApiScheduleInterval = "MINUTE"
	HOUR_ApiScheduleInterval   ApiScheduleInterval = "HOUR"
	DAY_ApiScheduleInterval    ApiScheduleInterval = "DAY"
	WEEK_ApiScheduleInterval   ApiScheduleInterval = "WEEK"
	MONTH_ApiScheduleInterval  ApiScheduleInterval = "MONTH"
	YEAR_ApiScheduleInterval   ApiScheduleInterval = "YEAR"
)
