/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// Replication arguments for Hive services.
type ApiHiveReplicationArguments struct {
	SourceService *ApiServiceRef `json:"sourceService,omitempty"`
	// Filters for tables to include in the replication. Optional. If not provided, include all tables in all databases.
	TableFilters []ApiHiveTable `json:"tableFilters,omitempty"`
	// Directory, in the HDFS service where the target Hive service's data is stored, where the export file will be saved. Optional. If not provided, Cloudera Manager will pick a directory for storing the data.
	ExportDir string `json:"exportDir,omitempty"`
	// Whether to force overwriting of mismatched tables.
	Force bool `json:"force,omitempty"`
	// Whether to replicate table data stored in HDFS. <p/> If set, the \"hdfsArguments\" property must be set to configure the HDFS replication job.
	ReplicateData bool                         `json:"replicateData,omitempty"`
	HdfsArguments *ApiHdfsReplicationArguments `json:"hdfsArguments,omitempty"`
	// Whether to replicate the impala metadata. (i.e. the metadata for impala UDFs and their corresponding binaries in HDFS).
	ReplicateImpalaMetadata bool `json:"replicateImpalaMetadata,omitempty"`
	// Whether to run invalidate metadata query or not
	RunInvalidateMetadata bool `json:"runInvalidateMetadata,omitempty"`
	// Whether to perform a dry run. Defaults to false.
	DryRun bool `json:"dryRun,omitempty"`
	// Number of threads to use in multi-threaded export/import phase
	NumThreads float64 `json:"numThreads,omitempty"`
}
