/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// Utilization report information of a Cluster.
type ApiClusterUtilization struct {
	// Average number of CPU cores available in the cluster during the report window.
	TotalCpuCores float64 `json:"totalCpuCores,omitempty"`
	// Average CPU consumption for the entire cluster during the report window. This includes consumption by user workloads in YARN and Impala, as well as consumption by all services running in the cluster.
	AvgCpuUtilization float64 `json:"avgCpuUtilization,omitempty"`
	// Maximum CPU consumption for the entire cluster during the report window. This includes consumption by user workloads in YARN and Impala, as well as consumption by all services running in the cluster.
	MaxCpuUtilization float64 `json:"maxCpuUtilization,omitempty"`
	// Average daily peak CPU consumption for the entire cluster during the report window. This includes consumption by user workloads in YARN and Impala, as well as consumption by all services running in the cluster.
	AvgCpuDailyPeak float64 `json:"avgCpuDailyPeak,omitempty"`
	// Average CPU consumption by workloads that ran on the cluster during the report window. This includes consumption by user workloads in YARN and Impala.
	AvgWorkloadCpu float64 `json:"avgWorkloadCpu,omitempty"`
	// Maximum CPU consumption by workloads that ran on the cluster during the report window. This includes consumption by user workloads in YARN and Impala.
	MaxWorkloadCpu float64 `json:"maxWorkloadCpu,omitempty"`
	// Average daily peak CPU consumption by workloads that ran on the cluster during the report window. This includes consumption by user workloads in YARN and Impala.
	AvgWorkloadCpuDailyPeak float64 `json:"avgWorkloadCpuDailyPeak,omitempty"`
	// Average physical memory (in bytes) available in the cluster during the report window. This includes consumption by user workloads in YARN and Impala, as well as consumption by all services running in the cluster.
	TotalMemory float64 `json:"totalMemory,omitempty"`
	// Average memory consumption (as percentage of total memory) for the entire cluster during the report window. This includes consumption by user workloads in YARN and Impala, as well as consumption by all services running in the cluster.
	AvgMemoryUtilization float64 `json:"avgMemoryUtilization,omitempty"`
	// Maximum memory consumption (as percentage of total memory) for the entire cluster during the report window. This includes consumption by user workloads in YARN and Impala, as well as consumption by all services running in the cluster.
	MaxMemoryUtilization float64 `json:"maxMemoryUtilization,omitempty"`
	// Average daily peak memory consumption (as percentage of total memory) for the entire cluster during the report window. This includes consumption by user workloads in YARN and Impala, as well as consumption by all services running in the cluster.
	AvgMemoryDailyPeak float64 `json:"avgMemoryDailyPeak,omitempty"`
	// Average memory consumption (as percentage of total memory) by workloads that ran on the cluster during the report window. This includes consumption by user workloads in YARN and Impala.
	AvgWorkloadMemory float64 `json:"avgWorkloadMemory,omitempty"`
	// Maximum memory consumption (as percentage of total memory) by workloads that ran on the cluster. This includes consumption by user workloads in YARN and Impala
	MaxWorkloadMemory float64 `json:"maxWorkloadMemory,omitempty"`
	// Average daily peak memory consumption (as percentage of total memory) by workloads that ran on the cluster during the report window. This includes consumption by user workloads in YARN and Impala.
	AvgWorkloadMemoryDailyPeak float64                   `json:"avgWorkloadMemoryDailyPeak,omitempty"`
	TenantUtilizations         *ApiTenantUtilizationList `json:"tenantUtilizations,omitempty"`
	// Timestamp corresponding to maximum CPU utilization for the entire cluster during the report window.
	MaxCpuUtilizationTimestampMs float64 `json:"maxCpuUtilizationTimestampMs,omitempty"`
	// Timestamp corresponding to maximum memory utilization for the entire cluster during the report window.
	MaxMemoryUtilizationTimestampMs float64 `json:"maxMemoryUtilizationTimestampMs,omitempty"`
	// Timestamp corresponds to maximum CPU consumption by workloads that ran on the cluster during the report window.
	MaxWorkloadCpuTimestampMs float64 `json:"maxWorkloadCpuTimestampMs,omitempty"`
	// Timestamp corresponds to maximum memory resource consumption by workloads that ran on the cluster during the report window.
	MaxWorkloadMemoryTimestampMs float64 `json:"maxWorkloadMemoryTimestampMs,omitempty"`
	// Error message while generating utilization report.
	ErrorMessage string `json:"errorMessage,omitempty"`
}
