/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ApiServiceState : Represents the configured run state of a service.
type ApiServiceState string

// List of ApiServiceState
const (
	HISTORY_NOT_AVAILABLE_ApiServiceState ApiServiceState = "HISTORY_NOT_AVAILABLE"
	UNKNOWN_ApiServiceState               ApiServiceState = "UNKNOWN"
	STARTING_ApiServiceState              ApiServiceState = "STARTING"
	STARTED_ApiServiceState               ApiServiceState = "STARTED"
	STOPPING_ApiServiceState              ApiServiceState = "STOPPING"
	STOPPED_ApiServiceState               ApiServiceState = "STOPPED"
	NA_ApiServiceState                    ApiServiceState = "NA"
)
