/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// HBase specific snapshot policy arguments.
type ApiHBaseSnapshotPolicyArguments struct {
	// The regular expressions specifying the tables. Tables matching any of them will be eligible for snapshot creation.
	TableRegExps []string `json:"tableRegExps,omitempty"`
	Storage      *Storage `json:"storage,omitempty"`
}
