/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ShutdownReadinessState : Enum for Cloudera Manager shutdown readiness state.
type ShutdownReadinessState string

// List of ShutdownReadinessState
const (
	READY_ShutdownReadinessState     ShutdownReadinessState = "READY"
	NOT_READY_ShutdownReadinessState ShutdownReadinessState = "NOT_READY"
)
