/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ApiCommissionState : Represents the Commission state of an entity.
type ApiCommissionState string

// List of ApiCommissionState
const (
	COMMISSIONED_ApiCommissionState    ApiCommissionState = "COMMISSIONED"
	DECOMMISSIONING_ApiCommissionState ApiCommissionState = "DECOMMISSIONING"
	DECOMMISSIONED_ApiCommissionState  ApiCommissionState = "DECOMMISSIONED"
	UNKNOWN_ApiCommissionState         ApiCommissionState = "UNKNOWN"
	OFFLINING_ApiCommissionState       ApiCommissionState = "OFFLINING"
	OFFLINED_ApiCommissionState        ApiCommissionState = "OFFLINED"
)
