/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// A service (such as HDFS, MapReduce, HBase) runs in a cluster. It has roles, which are the actual entities (NameNode, DataNodes, etc.) that perform the service's functions.  <h3>HDFS services and health checks</h3>  In CDH4, HDFS services may not present any health checks. This will happen if the service has more than one nameservice configured. In those cases, the health information will be available by fetching information about the nameservices instead. <p> The health summary is still available, and reflects a service-wide summary.
type ApiService struct {
	// The name of the service.
	Name string `json:"name,omitempty"`
	// The type of the service, e.g. HDFS, MAPREDUCE, HBASE.
	Type_         string            `json:"type,omitempty"`
	ClusterRef    *ApiClusterRef    `json:"clusterRef,omitempty"`
	ServiceState  *ApiServiceState  `json:"serviceState,omitempty"`
	HealthSummary *ApiHealthSummary `json:"healthSummary,omitempty"`
	// Readonly. Expresses whether the service configuration is stale.
	ConfigStale                 bool                      `json:"configStale,omitempty"`
	ConfigStalenessStatus       *ApiConfigStalenessStatus `json:"configStalenessStatus,omitempty"`
	ClientConfigStalenessStatus *ApiConfigStalenessStatus `json:"clientConfigStalenessStatus,omitempty"`
	// Readonly. The list of health checks of this service.
	HealthChecks []ApiHealthCheck `json:"healthChecks,omitempty"`
	// Readonly. Link into the Cloudera Manager web UI for this specific service.
	ServiceUrl string `json:"serviceUrl,omitempty"`
	// Readonly. Link into the Cloudera Manager web UI for role instances table for this specific service. Available since API v11.
	RoleInstancesUrl string `json:"roleInstancesUrl,omitempty"`
	// Readonly. Whether the service is in maintenance mode. Available since API v2.
	MaintenanceMode bool `json:"maintenanceMode,omitempty"`
	// Readonly. The list of objects that trigger this service to be in maintenance mode. Available since API v2.
	MaintenanceOwners []ApiEntityType   `json:"maintenanceOwners,omitempty"`
	Config            *ApiServiceConfig `json:"config,omitempty"`
	// The list of service roles. Optional.
	Roles []ApiRole `json:"roles,omitempty"`
	// The display name for the service that is shown in the UI. Available since API v2.
	DisplayName string `json:"displayName,omitempty"`
	// The list of role configuration groups in this service. Optional. Available since API v3.
	RoleConfigGroups []ApiRoleConfigGroup `json:"roleConfigGroups,omitempty"`
	// The list of replication schedules for this service. Optional. Available since API v6.
	ReplicationSchedules []ApiReplicationSchedule `json:"replicationSchedules,omitempty"`
	// The list of snapshot policies for this service. Optional. Available since API v6.
	SnapshotPolicies []ApiSnapshotPolicy `json:"snapshotPolicies,omitempty"`
	EntityStatus     *ApiEntityStatus    `json:"entityStatus,omitempty"`
}
