/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// This objects represents a deployment including all clusters, hosts, services, roles, etc in the system.  It can be used to save and restore all settings.
type ApiDeployment struct {
	// Readonly. This timestamp is provided when you request a deployment and is not required (or even read) when creating a deployment. This timestamp is useful if you have multiple deployments saved and want to determine which one to use as a restore point.
	Timestamp string `json:"timestamp,omitempty"`
	// List of clusters in the system including their services, roles and complete config values.
	Clusters []ApiCluster `json:"clusters,omitempty"`
	// List of hosts in the system
	Hosts []ApiHost `json:"hosts,omitempty"`
	// List of all users in the system
	Users             []ApiUser       `json:"users,omitempty"`
	VersionInfo       *ApiVersionInfo `json:"versionInfo,omitempty"`
	ManagementService *ApiService     `json:"managementService,omitempty"`
	ManagerSettings   *ApiConfigList  `json:"managerSettings,omitempty"`
	AllHostsConfig    *ApiConfigList  `json:"allHostsConfig,omitempty"`
	// The list of peers configured in Cloudera Manager. Available since API v3.
	Peers         []ApiCmPeer          `json:"peers,omitempty"`
	HostTemplates *ApiHostTemplateList `json:"hostTemplates,omitempty"`
}
