/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

type ApiActivityStatus string

// List of ApiActivityStatus
const (
	UNKNOWN_ApiActivityStatus           ApiActivityStatus = "UNKNOWN"
	SUBMITTED_ApiActivityStatus         ApiActivityStatus = "SUBMITTED"
	STARTED_ApiActivityStatus           ApiActivityStatus = "STARTED"
	SUSPENDED_ApiActivityStatus         ApiActivityStatus = "SUSPENDED"
	FAILED_ApiActivityStatus            ApiActivityStatus = "FAILED"
	KILLED_ApiActivityStatus            ApiActivityStatus = "KILLED"
	SUCCEEDED_ApiActivityStatus         ApiActivityStatus = "SUCCEEDED"
	ASSUMED_SUCCEEDED_ApiActivityStatus ApiActivityStatus = "ASSUMED_SUCCEEDED"
)
