/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

type ApiEventSeverity string

// List of ApiEventSeverity
const (
	UNKNOWN_ApiEventSeverity       ApiEventSeverity = "UNKNOWN"
	INFORMATIONAL_ApiEventSeverity ApiEventSeverity = "INFORMATIONAL"
	IMPORTANT_ApiEventSeverity     ApiEventSeverity = "IMPORTANT"
	CRITICAL_ApiEventSeverity      ApiEventSeverity = "CRITICAL"
)
