/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cm_api

// ApiEntityType : Represents the types of entities.
type ApiEntityType string

// List of ApiEntityType
const (
	CLUSTER_ApiEntityType ApiEntityType = "CLUSTER"
	SERVICE_ApiEntityType ApiEntityType = "SERVICE"
	ROLE_ApiEntityType    ApiEntityType = "ROLE"
	HOST_ApiEntityType    ApiEntityType = "HOST"
)
